### ISSUE TITLE
[OOB-5.11] Cannot pass compilation with IAR toolchain

### ISSUE THREAD

**Issue by soramame21** [ARMmbed/mbed-os-example-socket-stats#2]
Got a compilation failure with IAR toolchain as following.
The example worked well when compiling with ARM and GCC_ARM toolchain.

```
C:\ioT\511ooB\mbed-os-example-socket-stats>mbed compile -m K64F -t IAR -f -v -c
[mbed] Working path "C:\ioT\511ooB\mbed-os-example-socket-stats" (program)
[mbed] Auto-installing missing Python modules...
[mbed] Exec "C:\Python27\python.exe -u C:\ioT\511ooB\mbed-os-example-socket-stats\mbed-os\tools\make.py -t IAR -m K64F --source . --build .\BUILD\K64F\IAR -c -v" in "C:\ioT\511ooB\mbed-os-example-socket-stats"
Building project mbed-os-example-socket-stats (K64F, IAR)
Scan: mbed-os-example-socket-stats
Macros: -DTARGET_PSA -DDEVICE_EMAC=1 -D__MBED__=1 -DDEVICE_I2CSLAVE=1 -D__FPU_PRESENT=1 -DTARGET_Freescale -DDEVICE_PORTINOUT=1 -DTARGET_RTOS_M4_M7 -DDEVICE_RTC=1 -DCOMPONENT_PSA_SRV_EMUL=1 -DDEVICE_SERIAL_ASYNCH=1 -D__CMSIS_RTOS -DFSL_RTOS_MBED -DDEVICE_STORAGE=1 -DTARGET_KPSDK_MCUS -DDEVICE_USTICKER=1 -DDEVICE_CRC=1 -DTARGET_CORTEX_M -DTARGET_KSDK2_MCUS -DTARGET_LIKE_CORTEX_M4 -DDEVICE_ANALOGOUT=1 -DTARGET_M4 -DTARGET_K64F -DCOMPONENT_PSA_SRV_IMPL=1 -DDEVICE_SPI_ASYNCH=1 -DDEVICE_LPTICKER=1 -DTOOLCHAIN_IAR -DCOMPONENT_FLASHIAP=1 -DDEVICE_INTERRUPTIN=1 -DTARGET_Freescale_EMAC -DTARGET_CORTEX -DDEVICE_I2C=1 -DDEVICE_PORTOUT=1 -D__CORTEX_M4 -DDEVICE_STDIO_MESSAGES=1 -DCPU_MK64FN1M0VMD12 -DDEVICE_PWMOUT=1 -DTARGET_LIKE_MBED -DTARGET_FF_ARDUINO -DTARGET_KPSDK_CODE -DTARGET_RELEASE -DCOMPONENT_NSPE=1 -DDEVICE_SERIAL_FC=1 -DFEATURE_STORAGE=1 -DMBEDTLS_PSA_CRYPTO_C -DDEVICE_TRNG=1 -D__MBED_CMSIS_RTOS_CM -DDEVICE_SLEEP=1 -DTARGET_FRDM -DTARGET_MCUXpresso_MCUS -DDEVICE_SPI=1 -DCOMPONENT_SD=1 -DDEVICE_SPISLAVE=1 -DDEVICE_ANALOGIN=1 -DDEVICE_SERIAL=1 -DMBED_BUILD_TIMESTAMP=1543895297.76 -DDEVICE_FLASH=1 -DDEVICE_PORTIN=1 -DTARGET_MCU_K64F -DARM_MATH_CM4
Compile [  0.1%]: cmain.S
Compile: C:\Program Files (x86)\IAR Systems\Embedded Workbench 7.5\arm\bin\iasmarm --cpu Cortex-M4F -D__CORTEX_M4 -DCPU_MK64FN1M0VMD12 -DARM_MATH_CM4 -D__FPU_PRESENT=1 -D__MBED_CMSIS_RTOS_CM -D__CMSIS_RTOS -DFSL_RTOS_MBED -DMBEDTLS_PSA_CRYPTO_C -f .\BUILD\K64F\IAR\asm_macros_d2fe15eaf1dff27828989f0ed2293fa2.xcl -o BUILD\K64F\IAR\mbed-os\cmsis\TARGET_CORTEX_M\TOOLCHAIN_IAR\cmain.o .\mbed-os\cmsis\TARGET_CORTEX_M\TOOLCHAIN_IAR\cmain.S
[DEBUG] Return: 0
Compile [  0.3%]: except.S
Compile: C:\Program Files (x86)\IAR Systems\Embedded Workbench 7.5\arm\bin\iasmarm --cpu Cortex-M4F -D__CORTEX_M4 -DCPU_MK64FN1M0VMD12 -DARM_MATH_CM4 -D__FPU_PRESENT=1 -D__MBED_CMSIS_RTOS_CM -D__CMSIS_RTOS -DFSL_RTOS_MBED -DMBEDTLS_PSA_CRYPTO_C -f .\BUILD\K64F\IAR\asm_macros_d2fe15eaf1dff27828989f0ed2293fa2.xcl -o BUILD\K64F\IAR\mbed-os\cmsis\TARGET_CORTEX_M\TOOLCHAIN_IAR\except.o .\mbed-os\cmsis\TARGET_CORTEX_M\TOOLCHAIN_IAR\except.S
[DEBUG] Return: 0
Compile [  0.4%]: mbed_tz_context.c
Compile: C:\Program Files (x86)\IAR Systems\Embedded Workbench 7.5\arm\bin\iccarm --no_wrap_diagnostics -e --diag_suppress=Pa050,Pa084,Pa093,Pa082 -Oh --enable_restrict --cpu Cortex-M4F --thumb --dlib_config DLib_Config_Full.h --vla --diag_suppress=Pe546 -DMBED_ROM_START=0x0 -DMBED_ROM_SIZE=0x100000 -DMBED_RAM_START=0x20000000 -DMBED_RAM_SIZE=0x30000 -DMBED_RAM1_START=0x1fff0000 -DMBED_RAM1_SIZE=0x10000 -DTARGET_PSA -DDEVICE_EMAC=1 -D__MBED__=1 -DDEVICE_I2CSLAVE=1 -D__FPU_PRESENT=1 -DTARGET_Freescale -DDEVICE_PORTINOUT=1 -DTARGET_RTOS_M4_M7 -DDEVICE_RTC=1 -DCOMPONENT_PSA_SRV_EMUL=1 -DDEVICE_SERIAL_ASYNCH=1 -D__CMSIS_RTOS -DFSL_RTOS_MBED -DDEVICE_STORAGE=1 -DTARGET_KPSDK_MCUS -DDEVICE_USTICKER=1 -DDEVICE_CRC=1 -DTARGET_CORTEX_M -DTARGET_KSDK2_MCUS -DTARGET_LIKE_CORTEX_M4 -DDEVICE_ANALOGOUT=1 -DTARGET_M4 -DTARGET_K64F -DCOMPONENT_PSA_SRV_IMPL=1 -DDEVICE_SPI_ASYNCH=1 -DDEVICE_LPTICKER=1 -DTOOLCHAIN_IAR -DCOMPONENT_FLASHIAP=1 -DDEVICE_INTERRUPTIN=1 -DTARGET_Freescale_EMAC -DTARGET_CORTEX -DDEVICE_I2C=1 -DDEVICE_PORTOUT=1 -D__CORTEX_M4 -DDEVICE_STDIO_MESSAGES=1 -DCPU_MK64FN1M0VMD12 -DDEVICE_PWMOUT=1 -DTARGET_LIKE_MBED -DTARGET_FF_ARDUINO -DTARGET_KPSDK_CODE -DTARGET_RELEASE -DCOMPONENT_NSPE=1 -DDEVICE_SERIAL_FC=1 -DFEATURE_STORAGE=1 -DMBEDTLS_PSA_CRYPTO_C -DDEVICE_TRNG=1 -D__MBED_CMSIS_RTOS_CM -DDEVICE_SLEEP=1 -DTARGET_FRDM -DTARGET_MCUXpresso_MCUS -DDEVICE_SPI=1 -DCOMPONENT_SD=1 -DDEVICE_SPISLAVE=1 -DDEVICE_ANALOGIN=1 -DDEVICE_SERIAL=1 -DMBED_BUILD_TIMESTAMP=1543895297.76 -DDEVICE_FLASH=1 -DDEVICE_PORTIN=1 -DTARGET_MCU_K64F -DARM_MATH_CM4 -f .\BUILD\K64F\IAR\.includes_206fb217945c60f89d2df525b694797a.txt --preinclude=.\BUILD\K64F\IAR\mbed_config.h --dependencies BUILD\K64F\IAR\mbed-os\cmsis\TARGET_CORTEX_M\mbed_tz_context.d -l BUILD\K64F\IAR\mbed-os\cmsis\TARGET_CORTEX_M\mbed_tz_context.s.txt -o BUILD\K64F\IAR\mbed-os\cmsis\TARGET_CORTEX_M\mbed_tz_context.o .\mbed-os\cmsis\TARGET_CORTEX_M\mbed_tz_context.c
[DEBUG] Return: 0
Compile [  0.5%]: mbed_fault_handler.c
Compile: C:\Program Files (x86)\IAR Systems\Embedded Workbench 7.5\arm\bin\iccarm --no_wrap_diagnostics -e --diag_suppress=Pa050,Pa084,Pa093,Pa082 -Oh --enable_restrict --cpu Cortex-M4F --thumb --dlib_config DLib_Config_Full.h --vla --diag_suppress=Pe546 -DMBED_ROM_START=0x0 -DMBED_ROM_SIZE=0x100000 -DMBED_RAM_START=0x20000000 -DMBED_RAM_SIZE=0x30000 -DMBED_RAM1_START=0x1fff0000 -DMBED_RAM1_SIZE=0x10000 -DTARGET_PSA -DDEVICE_EMAC=1 -D__MBED__=1 -DDEVICE_I2CSLAVE=1 -D__FPU_PRESENT=1 -DTARGET_Freescale -DDEVICE_PORTINOUT=1 -DTARGET_RTOS_M4_M7 -DDEVICE_RTC=1 -DCOMPONENT_PSA_SRV_EMUL=1 -DDEVICE_SERIAL_ASYNCH=1 -D__CMSIS_RTOS -DFSL_RTOS_MBED -DDEVICE_STORAGE=1 -DTARGET_KPSDK_MCUS -DDEVICE_USTICKER=1 -DDEVICE_CRC=1 -DTARGET_CORTEX_M -DTARGET_KSDK2_MCUS -DTARGET_LIKE_CORTEX_M4 -DDEVICE_ANALOGOUT=1 -DTARGET_M4 -DTARGET_K64F -DCOMPONENT_PSA_SRV_IMPL=1 -DDEVICE_SPI_ASYNCH=1 -DDEVICE_LPTICKER=1 -DTOOLCHAIN_IAR -DCOMPONENT_FLASHIAP=1 -DDEVICE_INTERRUPTIN=1 -DTARGET_Freescale_EMAC -DTARGET_CORTEX -DDEVICE_I2C=1 -DDEVICE_PORTOUT=1 -D__CORTEX_M4 -DDEVICE_STDIO_MESSAGES=1 -DCPU_MK64FN1M0VMD12 -DDEVICE_PWMOUT=1 -DTARGET_LIKE_MBED -DTARGET_FF_ARDUINO -DTARGET_KPSDK_CODE -DTARGET_RELEASE -DCOMPONENT_NSPE=1 -DDEVICE_SERIAL_FC=1 -DFEATURE_STORAGE=1 -DMBEDTLS_PSA_CRYPTO_C -DDEVICE_TRNG=1 -D__MBED_CMSIS_RTOS_CM -DDEVICE_SLEEP=1 -DTARGET_FRDM -DTARGET_MCUXpresso_MCUS -DDEVICE_SPI=1 -DCOMPONENT_SD=1 -DDEVICE_SPISLAVE=1 -DDEVICE_ANALOGIN=1 -DDEVICE_SERIAL=1 -DMBED_BUILD_TIMESTAMP=1543895297.76 -DDEVICE_FLASH=1 -DDEVICE_PORTIN=1 -DTARGET_MCU_K64F -DARM_MATH_CM4 -f .\BUILD\K64F\IAR\.includes_206fb217945c60f89d2df525b694797a.txt --preinclude=.\BUILD\K64F\IAR\mbed_config.h --dependencies BUILD\K64F\IAR\mbed-os\cmsis\TARGET_CORTEX_M\mbed_fault_handler.d -l BUILD\K64F\IAR\mbed-os\cmsis\TARGET_CORTEX_M\mbed_fault_handler.s.txt -o BUILD\K64F\IAR\mbed-os\cmsis\TARGET_CORTEX_M\mbed_fault_handler.o .\mbed-os\cmsis\TARGET_CORTEX_M\mbed_fault_handler.c
[DEBUG] Return: 0
Compile [  0.7%]: at24mac.cpp
Compile: C:\Program Files (x86)\IAR Systems\Embedded Workbench 7.5\arm\bin\iccarm --no_wrap_diagnostics -e --diag_suppress=Pa050,Pa084,Pa093,Pa082 -Oh --enable_restrict --cpu Cortex-M4F --thumb --dlib_config DLib_Config_Full.h --c++ --no_rtti --no_exceptions --guard_calls --no_static_destruction -DMBED_ROM_START=0x0 -DMBED_ROM_SIZE=0x100000 -DMBED_RAM_START=0x20000000 -DMBED_RAM_SIZE=0x30000 -DMBED_RAM1_START=0x1fff0000 -DMBED_RAM1_SIZE=0x10000 -DTARGET_PSA -DDEVICE_EMAC=1 -D__MBED__=1 -DDEVICE_I2CSLAVE=1 -D__FPU_PRESENT=1 -DTARGET_Freescale -DDEVICE_PORTINOUT=1 -DTARGET_RTOS_M4_M7 -DDEVICE_RTC=1 -DCOMPONENT_PSA_SRV_EMUL=1 -DDEVICE_SERIAL_ASYNCH=1 -D__CMSIS_RTOS -DFSL_RTOS_MBED -DDEVICE_STORAGE=1 -DTARGET_KPSDK_MCUS -DDEVICE_USTICKER=1 -DDEVICE_CRC=1 -DTARGET_CORTEX_M -DTARGET_KSDK2_MCUS -DTARGET_LIKE_CORTEX_M4 -DDEVICE_ANALOGOUT=1 -DTARGET_M4 -DTARGET_K64F -DCOMPONENT_PSA_SRV_IMPL=1 -DDEVICE_SPI_ASYNCH=1 -DDEVICE_LPTICKER=1 -DTOOLCHAIN_IAR -DCOMPONENT_FLASHIAP=1 -DDEVICE_INTERRUPTIN=1 -DTARGET_Freescale_EMAC -DTARGET_CORTEX -DDEVICE_I2C=1 -DDEVICE_PORTOUT=1 -D__CORTEX_M4 -DDEVICE_STDIO_MESSAGES=1 -DCPU_MK64FN1M0VMD12 -DDEVICE_PWMOUT=1 -DTARGET_LIKE_MBED -DTARGET_FF_ARDUINO -DTARGET_KPSDK_CODE -DTARGET_RELEASE -DCOMPONENT_NSPE=1 -DDEVICE_SERIAL_FC=1 -DFEATURE_STORAGE=1 -DMBEDTLS_PSA_CRYPTO_C -DDEVICE_TRNG=1 -D__MBED_CMSIS_RTOS_CM -DDEVICE_SLEEP=1 -DTARGET_FRDM -DTARGET_MCUXpresso_MCUS -DDEVICE_SPI=1 -DCOMPONENT_SD=1 -DDEVICE_SPISLAVE=1 -DDEVICE_ANALOGIN=1 -DDEVICE_SERIAL=1 -DMBED_BUILD_TIMESTAMP=1543895297.76 -DDEVICE_FLASH=1 -DDEVICE_PORTIN=1 -DTARGET_MCU_K64F -DARM_MATH_CM4 -f .\BUILD\K64F\IAR\.includes_206fb217945c60f89d2df525b694797a.txt --preinclude=.\BUILD\K64F\IAR\mbed_config.h --dependencies BUILD\K64F\IAR\mbed-os\components\802.15.4_RF\atmel-rf-driver\source\at24mac.d -l BUILD\K64F\IAR\mbed-os\components\802.15.4_RF\atmel-rf-driver\source\at24mac.s.txt -o BUILD\K64F\IAR\mbed-os\components\802.15.4_RF\atmel-rf-driver\source\at24mac.o .\mbed-os\components\802.15.4_RF\atmel-rf-driver\source\at24mac.cpp
[DEBUG] Return: 0
Compile [  0.8%]: MCR20Drv.c
Compile: C:\Program Files (x86)\IAR Systems\Embedded Workbench 7.5\arm\bin\iccarm --no_wrap_diagnostics -e --diag_suppress=Pa050,Pa084,Pa093,Pa082 -Oh --enable_restrict --cpu Cortex-M4F --thumb --dlib_config DLib_Config_Full.h --vla --diag_suppress=Pe546 -DMBED_ROM_START=0x0 -DMBED_ROM_SIZE=0x100000 -DMBED_RAM_START=0x20000000 -DMBED_RAM_SIZE=0x30000 -DMBED_RAM1_START=0x1fff0000 -DMBED_RAM1_SIZE=0x10000 -DTARGET_PSA -DDEVICE_EMAC=1 -D__MBED__=1 -DDEVICE_I2CSLAVE=1 -D__FPU_PRESENT=1 -DTARGET_Freescale -DDEVICE_PORTINOUT=1 -DTARGET_RTOS_M4_M7 -DDEVICE_RTC=1 -DCOMPONENT_PSA_SRV_EMUL=1 -DDEVICE_SERIAL_ASYNCH=1 -D__CMSIS_RTOS -DFSL_RTOS_MBED -DDEVICE_STORAGE=1 -DTARGET_KPSDK_MCUS -DDEVICE_USTICKER=1 -DDEVICE_CRC=1 -DTARGET_CORTEX_M -DTARGET_KSDK2_MCUS -DTARGET_LIKE_CORTEX_M4 -DDEVICE_ANALOGOUT=1 -DTARGET_M4 -DTARGET_K64F -DCOMPONENT_PSA_SRV_IMPL=1 -DDEVICE_SPI_ASYNCH=1 -DDEVICE_LPTICKER=1 -DTOOLCHAIN_IAR -DCOMPONENT_FLASHIAP=1 -DDEVICE_INTERRUPTIN=1 -DTARGET_Freescale_EMAC -DTARGET_CORTEX -DDEVICE_I2C=1 -DDEVICE_PORTOUT=1 -D__CORTEX_M4 -DDEVICE_STDIO_MESSAGES=1 -DCPU_MK64FN1M0VMD12 -DDEVICE_PWMOUT=1 -DTARGET_LIKE_MBED -DTARGET_FF_ARDUINO -DTARGET_KPSDK_CODE -DTARGET_RELEASE -DCOMPONENT_NSPE=1 -DDEVICE_SERIAL_FC=1 -DFEATURE_STORAGE=1 -DMBEDTLS_PSA_CRYPTO_C -DDEVICE_TRNG=1 -D__MBED_CMSIS_RTOS_CM -DDEVICE_SLEEP=1 -DTARGET_FRDM -DTARGET_MCUXpresso_MCUS -DDEVICE_SPI=1 -DCOMPONENT_SD=1 -DDEVICE_SPISLAVE=1 -DDEVICE_ANALOGIN=1 -DDEVICE_SERIAL=1 -DMBED_BUILD_TIMESTAMP=1543895297.76 -DDEVICE_FLASH=1 -DDEVICE_PORTIN=1 -DTARGET_MCU_K64F -DARM_MATH_CM4 -f .\BUILD\K64F\IAR\.includes_206fb217945c60f89d2df525b694797a.txt --preinclude=.\BUILD\K64F\IAR\mbed_config.h --dependencies BUILD\K64F\IAR\mbed-os\components\802.15.4_RF\mcr20a-rf-driver\source\MCR20Drv.d -l BUILD\K64F\IAR\mbed-os\components\802.15.4_RF\mcr20a-rf-driver\source\MCR20Drv.s.txt -o BUILD\K64F\IAR\mbed-os\components\802.15.4_RF\mcr20a-rf-driver\source\MCR20Drv.o .\mbed-os\components\802.15.4_RF\mcr20a-rf-driver\source\MCR20Drv.c
[DEBUG] Return: 0
Compile [  0.9%]: main.cpp
Compile: C:\Program Files (x86)\IAR Systems\Embedded Workbench 7.5\arm\bin\iccarm --no_wrap_diagnostics -e --diag_suppress=Pa050,Pa084,Pa093,Pa082 -Oh --enable_restrict --cpu Cortex-M4F --thumb --dlib_config DLib_Config_Full.h --c++ --no_rtti --no_exceptions --guard_calls --no_static_destruction -DMBED_ROM_START=0x0 -DMBED_ROM_SIZE=0x100000 -DMBED_RAM_START=0x20000000 -DMBED_RAM_SIZE=0x30000 -DMBED_RAM1_START=0x1fff0000 -DMBED_RAM1_SIZE=0x10000 -DTARGET_PSA -DDEVICE_EMAC=1 -D__MBED__=1 -DDEVICE_I2CSLAVE=1 -D__FPU_PRESENT=1 -DTARGET_Freescale -DDEVICE_PORTINOUT=1 -DTARGET_RTOS_M4_M7 -DDEVICE_RTC=1 -DCOMPONENT_PSA_SRV_EMUL=1 -DDEVICE_SERIAL_ASYNCH=1 -D__CMSIS_RTOS -DFSL_RTOS_MBED -DDEVICE_STORAGE=1 -DTARGET_KPSDK_MCUS -DDEVICE_USTICKER=1 -DDEVICE_CRC=1 -DTARGET_CORTEX_M -DTARGET_KSDK2_MCUS -DTARGET_LIKE_CORTEX_M4 -DDEVICE_ANALOGOUT=1 -DTARGET_M4 -DTARGET_K64F -DCOMPONENT_PSA_SRV_IMPL=1 -DDEVICE_SPI_ASYNCH=1 -DDEVICE_LPTICKER=1 -DTOOLCHAIN_IAR -DCOMPONENT_FLASHIAP=1 -DDEVICE_INTERRUPTIN=1 -DTARGET_Freescale_EMAC -DTARGET_CORTEX -DDEVICE_I2C=1 -DDEVICE_PORTOUT=1 -D__CORTEX_M4 -DDEVICE_STDIO_MESSAGES=1 -DCPU_MK64FN1M0VMD12 -DDEVICE_PWMOUT=1 -DTARGET_LIKE_MBED -DTARGET_FF_ARDUINO -DTARGET_KPSDK_CODE -DTARGET_RELEASE -DCOMPONENT_NSPE=1 -DDEVICE_SERIAL_FC=1 -DFEATURE_STORAGE=1 -DMBEDTLS_PSA_CRYPTO_C -DDEVICE_TRNG=1 -D__MBED_CMSIS_RTOS_CM -DDEVICE_SLEEP=1 -DTARGET_FRDM -DTARGET_MCUXpresso_MCUS -DDEVICE_SPI=1 -DCOMPONENT_SD=1 -DDEVICE_SPISLAVE=1 -DDEVICE_ANALOGIN=1 -DDEVICE_SERIAL=1 -DMBED_BUILD_TIMESTAMP=1543895297.76 -DDEVICE_FLASH=1 -DDEVICE_PORTIN=1 -DTARGET_MCU_K64F -DARM_MATH_CM4 -f .\BUILD\K64F\IAR\.includes_206fb217945c60f89d2df525b694797a.txt --preinclude=.\BUILD\K64F\IAR\mbed_config.h --dependencies BUILD\K64F\IAR\main.d -l BUILD\K64F\IAR\main.s.txt -o BUILD\K64F\IAR\main.o .\main.cpp
[DEBUG] Return: 3
[DEBUG] Output: Internal error: [Front end]: assertion failed at: "..\..\Translator\compiler_core\src\parser\edg\decl_inits.c", line 2031
[DEBUG] Output:
[DEBUG] Output:
[DEBUG] Output: Fatal error detected, aborting.
Traceback (most recent call last):
  File "C:\ioT\511ooB\mbed-os-example-socket-stats\mbed-os\tools\make.py", line 73, in wrapped_build_project
    src_dir, build_dir, mcu, *args, **kwargs
  File "C:\ioT\511ooB\mbed-os-example-socket-stats\mbed-os\tools\build_api.py", line 540, in build_project
    objects = toolchain.compile_sources(resources, sorted(resources.get_file_paths(FileType.INC_DIR)))
  File "C:\ioT\511ooB\mbed-os-example-socket-stats\mbed-os\tools\toolchains\__init__.py", line 413, in compile_sources
    return self.compile_queue(queue, objects)
  File "C:\ioT\511ooB\mbed-os-example-socket-stats\mbed-os\tools\toolchains\__init__.py", line 476, in compile_queue
    raise ToolException(err)
ToolException: Internal error: [Front end]: assertion failed at: "..\..\Translator\compiler_core\src\parser\edg\decl_inits.c", line 2031


Fatal error detected, aborting.

[mbed] ERROR: "C:\Python27\python.exe" returned error.
       Code: 1
       Path: "C:\ioT\511ooB\mbed-os-example-socket-stats"
       Command: "C:\Python27\python.exe -u C:\ioT\511ooB\mbed-os-example-socket-stats\mbed-os\tools\make.py -t IAR -m K64F --source . --build .\BUILD\K64F\IAR -c -v"
       Tip: You could retry the last command with "-v" flag for verbose output
---
```

**Comment by MarceloSalazar** [comment]
@soramame21
Can you please confirm the version of IAR you're using? (you can check with iccarm)
Also please confirm you're using the 'mbed-os-5.11.0-oob' branch. Thanks!

**Comment by soramame21** [comment]
@MarceloSalazar I'm using the 'mbed-os-5.11.0-oob' branch.
IAR version is  V7.80.4.12462/W32

**Comment by adbridge** [comment]
@soramame21 Could you please test if the fix @deepikabhavnani made to the oob branch has fixed this?

**Comment by soramame21** [comment]
@adbridge I'll test it on Friday, we have a big event now.

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/MBOCUSTRIA-265*
